language: ruby
rvm:
- 2.3.1

install: gem install jekyll html-proofer
script: sed -i -- 's/https:\/\/bugtrackr.github.io/http:\/\/127.0.0.1:4000/g' _config.yml
script: jekyll build && htmlproofer ./_site

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build

